# https://snapcraft.io/docs/snapcraft-yaml-reference
name: pdf-question-spacer
version: git
summary: Add whitespace to pdfs
description: |
  pdf-question-spacer is a tool used to add whitespace to pdfs. It allows for the addition of whitespace to sections of a pdf matching a regular expression, whilst also ensuring page breaks do not cut off shifted text. Alternatively, the user can select which regions of the pdf to add whitespace to interactively.

confinement: strict
base: core20
parts:
  pdf-question-spacer:
    plugin: python
    #python-version: python3
    source: https://github.com/laurencewarne/pdf-question-spacer.git
    stage-packages:
      - imagemagick
      - ffmpeg
      - libsm6
      - libxext6
      - poppler-utils
      - python3-tk
      - python3-dev
      - python3-pyqt5
      - build-essential
    organize:
      usr/bin/convert-im6.q16: usr/bin/convert
  
apps:
  # pdf-question-spacer:
  #   command: bin/pdf-question-spacer
  space-pdf-interactive:
    command: bin/space-pdf-interactive
    plugs:
      - home
      - wayland
      - x11
      - desktop
      - desktop-legacy
      - gsettings
      - opengl
      - network
