name: ci

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Run tests
        run: |
          python setup.py install
          python -m unittest discover -s tests -p '*test.py'
      ################
      # Publish snap #
      ################
      - uses: snapcore/action-build@v1
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        id: build
      - uses: snapcore/action-publish@v1
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          store_login: ${{ secrets.STORE_LOGIN }}
          snap: ${{ steps.build.outputs.snap }}
          release: edge
